def get_table_schema():
    page = {
            'WebHouseCase': {
                'KeyinDate': '',
                'idx': '',
                'CaseFrom': '',
                'CaseNo': '',
                'CaseName': '',
                'CaseUse': '',
                'SimpAddress': '',
                'City': '',
                'District': '',
                'Road': '',
                'CaseClass1': '',
                'CaseClass2': '',
                'CaseClass3': '',
                'CaseClass4': '',
                'HouseLayout': '',
                'Rm': '',
                'LivingRm': '',
                'BathRm': '',
                'spaceRm': '',
                'FloorSt': '',
                'FloorEn': '',
                'UpFloor': '',
                'TotalPrice': 0,
                'OrigPrice': 0,
                'Unit': '',
                'UnitPrice': 0.0,
                'UnitPriceUnit': '',
                'BuildPin': 0,
                'LandPin': 0,
                'CasePic': 0,
                'CasePicUrl': '',
                'CaseUrl': '',
                'CaseSystem': '',
                'RorS': '',
                'ParkSpace': '',
                'HouseAge': '',
                'Lat': '',
                'Lng': '',
                'MainPin': 0,
                'BudName': '',
                'ComUsePin': 0,
                'AttachedPin': 0
            },
            'WebHouseCasePart2': {
                'idx': '',
                'ContactUser': '',
                'ContactStore': '',
                'ContactTel': '',
                'ContactRole': '',
                'ContactAddr': '',
                'ContactEMail': '',
                'CaseFrom': '',
                'RorS': '',
                'ManagementFee': '',
                'ExpiryDate': '',
                'Lease': '',
                'Decorating': '',
                'ShortRentDeadline':'' 
            },
            'WebHouseCasePart3': {
                'idx': '',
                'Direction': '',
                'PrimarySchool': '',
                'HighSchool': '',
                'OthersPin': '',
                'MrtLine': '',
                'Characteristic': '',
                'CaseFrom': '',
                'RorS': '',
                'TotalPin': '',
                'Bus':'',
                'PublicRatios': '',
                'CMC': '',
                'BudUrl':''
            },
    }

    return page
